/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROJECT_H_RPCGEN
#define _PROJECT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DATE_PROG 0x31234567
#define DATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DATE 1
extern  char ** get_date(long *, CLIENT *);
extern  char ** get_date_svc(long *, struct svc_req *);
#define MEMORY 2
extern  double * get_memory(void *, CLIENT *);
extern  double * get_memory_svc(void *, struct svc_req *);
#define PROCESS 3
extern  double * get_load_procs(void *, CLIENT *);
extern  double * get_load_procs_svc(void *, struct svc_req *);
#define CPU 4
extern  double * get_cpu(void *, CLIENT *);
extern  double * get_cpu_svc(void *, struct svc_req *);
extern int date_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DATE 1
extern  char ** get_date();
extern  char ** get_date_svc();
#define MEMORY 2
extern  double * get_memory();
extern  double * get_memory_svc();
#define PROCESS 3
extern  double * get_load_procs();
extern  double * get_load_procs_svc();
#define CPU 4
extern  double * get_cpu();
extern  double * get_cpu_svc();
extern int date_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROJECT_H_RPCGEN */
