package OrderManagementApp;


/**
* OrderManagementApp/InvalidOrder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
* Monday, March 24, 2025 3:16:51 PM CDT
*/

public final class InvalidOrder extends org.omg.CORBA.UserException
{
  public String message = null;

  public InvalidOrder ()
  {
    super(InvalidOrderHelper.id());
  } // ctor

  public InvalidOrder (String _message)
  {
    super(InvalidOrderHelper.id());
    message = _message;
  } // ctor


  public InvalidOrder (String $reason, String _message)
  {
    super(InvalidOrderHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InvalidOrder
