package OrderManagementApp;

/**
* OrderManagementApp/InvalidOrderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
* Monday, March 24, 2025 3:16:51 PM CDT
*/

public final class InvalidOrderHolder implements org.omg.CORBA.portable.Streamable
{
  public OrderManagementApp.InvalidOrder value = null;

  public InvalidOrderHolder ()
  {
  }

  public InvalidOrderHolder (OrderManagementApp.InvalidOrder initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrderManagementApp.InvalidOrderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrderManagementApp.InvalidOrderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrderManagementApp.InvalidOrderHelper.type ();
  }

}
