package OrderManagementApp;


/**
* OrderManagementApp/OrderManagementPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
* Monday, March 24, 2025 3:16:51 PM CDT
*/

public abstract class OrderManagementPOA extends org.omg.PortableServer.Servant
 implements OrderManagementApp.OrderManagementOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("viewMenu", new java.lang.Integer (0));
    _methods.put ("placeOrder", new java.lang.Integer (1));
    _methods.put ("checkOrderStatus", new java.lang.Integer (2));
    _methods.put ("viewCurrentOrders", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Customer
       case 0:  // OrderManagementApp/OrderManagement/viewMenu
       {
         String $result = null;
         $result = this.viewMenu ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // OrderManagementApp/OrderManagement/placeOrder
       {
         try {
           String username = in.read_string ();
           int chickenQty = in.read_long ();
           int colaQty = in.read_long ();
           String $result = null;
           $result = this.placeOrder (username, chickenQty, colaQty);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (OrderManagementApp.InvalidOrder $ex) {
           out = $rh.createExceptionReply ();
           OrderManagementApp.InvalidOrderHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // OrderManagementApp/OrderManagement/checkOrderStatus
       {
         try {
           String username = in.read_string ();
           OrderManagementApp.Order $result = null;
           $result = this.checkOrderStatus (username);
           out = $rh.createReply();
           OrderManagementApp.OrderHelper.write (out, $result);
         } catch (OrderManagementApp.InvalidOrder $ex) {
           out = $rh.createExceptionReply ();
           OrderManagementApp.InvalidOrderHelper.write (out, $ex);
         }
         break;
       }


  // Manager
       case 3:  // OrderManagementApp/OrderManagement/viewCurrentOrders
       {
         OrderManagementApp.Order $result[] = null;
         $result = this.viewCurrentOrders ();
         out = $rh.createReply();
         OrderManagementApp.OrderListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OrderManagementApp/OrderManagement:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public OrderManagement _this() 
  {
    return OrderManagementHelper.narrow(
    super._this_object());
  }

  public OrderManagement _this(org.omg.CORBA.ORB orb) 
  {
    return OrderManagementHelper.narrow(
    super._this_object(orb));
  }


} // class OrderManagementPOA
