package OrderManagementApp;


/**
* OrderManagementApp/OrderManagementHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
* Monday, March 24, 2025 3:16:51 PM CDT
*/

abstract public class OrderManagementHelper
{
  private static String  _id = "IDL:OrderManagementApp/OrderManagement:1.0";

  public static void insert (org.omg.CORBA.Any a, OrderManagementApp.OrderManagement that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OrderManagementApp.OrderManagement extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OrderManagementApp.OrderManagementHelper.id (), "OrderManagement");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OrderManagementApp.OrderManagement read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OrderManagementStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OrderManagementApp.OrderManagement value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OrderManagementApp.OrderManagement narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OrderManagementApp.OrderManagement)
      return (OrderManagementApp.OrderManagement)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OrderManagementApp._OrderManagementStub stub = new OrderManagementApp._OrderManagementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OrderManagementApp.OrderManagement unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OrderManagementApp.OrderManagement)
      return (OrderManagementApp.OrderManagement)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OrderManagementApp._OrderManagementStub stub = new OrderManagementApp._OrderManagementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
