package OrderManagementApp;


/**
* OrderManagementApp/OrderListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
* Monday, March 24, 2025 3:16:51 PM CDT
*/

public final class OrderListHolder implements org.omg.CORBA.portable.Streamable
{
  public OrderManagementApp.Order value[] = null;

  public OrderListHolder ()
  {
  }

  public OrderListHolder (OrderManagementApp.Order[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrderManagementApp.OrderListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrderManagementApp.OrderListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrderManagementApp.OrderListHelper.type ();
  }

}
