package OrderManagementApp;

/**
* OrderManagementApp/OrderManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
* Monday, March 24, 2025 3:16:51 PM CDT
*/

public final class OrderManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public OrderManagementApp.OrderManagement value = null;

  public OrderManagementHolder ()
  {
  }

  public OrderManagementHolder (OrderManagementApp.OrderManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrderManagementApp.OrderManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrderManagementApp.OrderManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrderManagementApp.OrderManagementHelper.type ();
  }

}
