package OrderManagementApp;


/**
* OrderManagementApp/OrderManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
* Monday, March 24, 2025 3:16:51 PM CDT
*/

public interface OrderManagementOperations 
{

  // Customer
  String viewMenu ();
  String placeOrder (String username, int chickenQty, int colaQty) throws OrderManagementApp.InvalidOrder;
  OrderManagementApp.Order checkOrderStatus (String username) throws OrderManagementApp.InvalidOrder;

  // Manager
  OrderManagementApp.Order[] viewCurrentOrders ();
} // interface OrderManagementOperations
