package OrderManagementApp;


/**
* OrderManagementApp/Order.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
* Monday, March 24, 2025 3:16:51 PM CDT
*/

public final class Order implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int chickenQty = (int)0;
  public int colaQty = (int)0;
  public double totalPrice = (double)0;

  public Order ()
  {
  } // ctor

  public Order (String _username, int _chickenQty, int _colaQty, double _totalPrice)
  {
    username = _username;
    chickenQty = _chickenQty;
    colaQty = _colaQty;
    totalPrice = _totalPrice;
  } // ctor

} // class Order
